
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Nov 11 2019 23:07:53 IST (Nov 11 2019 17:37:53 UTC)

// Verification Directory fv/nine_st_fsm 

module nine_st_fsm(CLK, RESET, ONE, ZERO, OUT);
  input CLK, RESET, ONE, ZERO;
  output OUT;
  wire CLK, RESET, ONE, ZERO;
  wire OUT;
  wire [3:0] st;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34;
  DFFQX1 \st_reg[2] (.CK (CLK), .D (n_34), .Q (st[2]));
  OAI211XL g1795(.A0 (n_28), .A1 (n_7), .B0 (n_20), .C0 (n_33), .Y
       (n_34));
  DFFQX1 \st_reg[3] (.CK (CLK), .D (n_32), .Q (st[3]));
  DFFQX1 \st_reg[0] (.CK (CLK), .D (n_31), .Q (st[0]));
  OAI21XL g1798(.A0 (n_27), .A1 (n_22), .B0 (st[2]), .Y (n_33));
  NOR2XL g1800(.A (RESET), .B (n_30), .Y (n_32));
  DFFQX1 \st_reg[1] (.CK (CLK), .D (n_29), .Q (st[1]));
  OAI211XL g1799(.A0 (n_26), .A1 (n_16), .B0 (n_23), .C0 (n_24), .Y
       (n_31));
  AOI21XL g1803(.A0 (st[2]), .A1 (n_19), .B0 (st[3]), .Y (n_30));
  OAI221XL g1801(.A0 (n_13), .A1 (n_25), .B0 (n_28), .B1 (n_15), .C0
       (n_21), .Y (n_29));
  OAI22XL g1805(.A0 (n_26), .A1 (st[0]), .B0 (n_25), .B1 (st[1]), .Y
       (n_27));
  NAND3BXL g1802(.AN (n_25), .B (st[2]), .C (n_18), .Y (n_24));
  AOI22XL g1804(.A0 (n_8), .A1 (n_10), .B0 (n_22), .B1 (st[0]), .Y
       (n_23));
  NAND2XL g1806(.A (st[1]), .B (n_22), .Y (n_21));
  NAND3XL g1807(.A (n_12), .B (n_11), .C (n_14), .Y (n_20));
  OAI32XL g1813(.A0 (n_6), .A1 (ZERO), .A2 (n_18), .B0 (n_5), .B1
       (n_9), .Y (n_19));
  AOI211XL g1808(.A0 (st[2]), .A1 (st[1]), .B0 (n_14), .C0 (n_3), .Y
       (n_15));
  AOI22XL g1812(.A0 (n_4), .A1 (n_12), .B0 (n_2), .B1 (st[1]), .Y
       (n_13));
  NOR2XL g1809(.A (n_11), .B (n_10), .Y (n_26));
  NAND2XL g1811(.A (n_9), .B (n_11), .Y (n_25));
  AOI2BB1XL g1810(.A0N (n_1), .A1N (st[3]), .B0 (RESET), .Y (n_22));
  MXI2XL g1815(.A (n_18), .B (st[0]), .S0 (n_12), .Y (n_8));
  INVXL g1816(.A (n_10), .Y (n_28));
  AOI21XL g1818(.A0 (st[0]), .A1 (n_12), .B0 (st[1]), .Y (n_7));
  NOR3XL g1819(.A (RESET), .B (n_6), .C (st[3]), .Y (n_11));
  INVXL g1823(.A (n_4), .Y (n_5));
  NOR3XL g1817(.A (RESET), .B (n_9), .C (st[3]), .Y (n_10));
  INVXL g1820(.A (n_3), .Y (n_16));
  INVXL g1824(.A (n_18), .Y (n_14));
  NOR2XL g1825(.A (st[1]), .B (n_2), .Y (n_4));
  NOR2XL g1822(.A (st[0]), .B (st[1]), .Y (n_3));
  NOR2XL g1821(.A (ZERO), .B (ONE), .Y (n_1));
  NAND2XL g1826(.A (st[0]), .B (st[1]), .Y (n_18));
  INVXL g1829(.A (ONE), .Y (n_6));
  INVXL g1828(.A (st[0]), .Y (n_2));
  INVXL g1830(.A (ZERO), .Y (n_9));
  INVXL g1831(.A (st[2]), .Y (n_12));
  NOR3BXL g2(.AN (st[3]), .B (st[2]), .C (n_16), .Y (OUT));
endmodule

